<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Uninstall-Opticon</AssemblyName>
    <RootNamespace>Taildesk.Uninstaller</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\assets\opticon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
