using System.Diagnostics;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Taildesk.Shared;

namespace Taildesk.Admin;

/// <summary>
/// The short-lived access grant returned by the target Agent after it installs
/// the public half of a key generated by <see cref="SshSessionLauncher"/>.
/// </summary>
public sealed record SshSessionLaunchOptions
{
    public required string ExpectedHost { get; init; }
    public TimeSpan RequestedLifetime { get; init; } = TimeSpan.FromHours(1);
    public string? SshExecutable { get; init; }
    public string? SshKeygenExecutable { get; init; }
    public string? RemoteCommand { get; init; }
    public string? PowerShellEncodedCommand { get; init; }
    public bool AllocateTerminal { get; init; } = true;
}

public delegate Task<SshAccessResponse> SshSessionProvisioner(
    string ephemeralPublicKey,
    TimeSpan requestedLifetime,
    CancellationToken cancellationToken);

public delegate Task SshSessionRevoker(string sessionId, CancellationToken cancellationToken);

internal sealed class LoopbackSshRelay : IAsyncDisposable
{
    private readonly TcpListener _listener;
    private readonly string _targetHost;
    private readonly int _targetPort;
    private readonly CancellationTokenSource _shutdown = new();
    private readonly object _sync = new();
    private readonly HashSet<Task> _connections = [];
    private readonly Task _acceptLoop;

    public LoopbackSshRelay(string targetHost, int targetPort)
    {
        _targetHost = targetHost;
        _targetPort = targetPort;
        _listener = new TcpListener(IPAddress.Loopback, 0);
        _listener.Start(4);
        Port = ((IPEndPoint)_listener.LocalEndpoint).Port;
        _acceptLoop = AcceptLoopAsync();
    }

    public string Host => IPAddress.Loopback.ToString();
    public int Port { get; }

    public async ValueTask DisposeAsync()
    {
        if (_shutdown.IsCancellationRequested) return;
        await _shutdown.CancelAsync();
        _listener.Stop();
        try { await _acceptLoop; }
        catch (OperationCanceledException) { }
        catch (SocketException) when (_shutdown.IsCancellationRequested) { }

        Task[] connections;
        lock (_sync) connections = [.. _connections];
        try { await Task.WhenAll(connections); }
        catch (OperationCanceledException) { }
        catch (SocketException) when (_shutdown.IsCancellationRequested) { }
        finally { _shutdown.Dispose(); }
    }

    private async Task AcceptLoopAsync()
    {
        while (!_shutdown.IsCancellationRequested)
        {
            var client = await _listener.AcceptTcpClientAsync(_shutdown.Token);
            var connection = RelayAsync(client, _shutdown.Token);
            lock (_sync) _connections.Add(connection);
            _ = connection.ContinueWith(
                completed =>
                {
                    lock (_sync) _connections.Remove(completed);
                },
                CancellationToken.None,
                TaskContinuationOptions.ExecuteSynchronously,
                TaskScheduler.Default);
        }
    }

    private async Task RelayAsync(TcpClient client, CancellationToken cancellationToken)
    {
        using (client)
        using (var target = new TcpClient())
        {
            await target.ConnectAsync(_targetHost, _targetPort, cancellationToken);
            await using var clientStream = client.GetStream();
            await using var targetStream = target.GetStream();
            using var connectionEnded = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            var upstream = clientStream.CopyToAsync(targetStream, connectionEnded.Token);
            var downstream = targetStream.CopyToAsync(clientStream, connectionEnded.Token);
            await Task.WhenAny(upstream, downstream);
            await connectionEnded.CancelAsync();
            try { await Task.WhenAll(upstream, downstream); }
            catch (OperationCanceledException) when (connectionEnded.IsCancellationRequested) { }
        }
    }
}

/// <summary>
/// Owns a running interactive ssh.exe process and its ephemeral local key files.
/// Cleanup and remote revocation happen automatically when ssh.exe exits.
/// </summary>
public sealed class SshSessionHandle : IAsyncDisposable
{
    private readonly Process _process;
    private readonly string _sessionDirectory;
    private readonly string _privateKeyPath;
    private readonly SshSessionRevoker? _revoker;
    private readonly LoopbackSshRelay _relay;
    private int _cleanupStarted;
    private int _disposed;

    internal SshSessionHandle(
        Process process,
        SshAccessResponse grant,
        string sessionDirectory,
        string privateKeyPath,
        SshSessionRevoker? revoker,
        LoopbackSshRelay relay)
    {
        _process = process;
        Grant = grant;
        _sessionDirectory = sessionDirectory;
        _privateKeyPath = privateKeyPath;
        _revoker = revoker;
        _relay = relay;
        Completion = MonitorAsync();
    }

    public SshAccessResponse Grant { get; }
    public Process Process => _process;
    public Task<int> Completion { get; }
    public Exception? RemoteRevocationError { get; private set; }
    public Exception? LocalCleanupError { get; private set; }
    public Exception? CleanupError { get; private set; }

    public Task<int> WaitForExitAsync(CancellationToken cancellationToken = default) =>
        Completion.WaitAsync(cancellationToken);

    /// <summary>
    /// Revokes the remote key and removes local key material without terminating
    /// an already authenticated shell. Use <see cref="TerminateAsync"/> to close it.
    /// </summary>
    public Task CleanupAsync() => CleanupCoreAsync();

    public async Task TerminateAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            if (!_process.HasExited) _process.Kill(entireProcessTree: true);
        }
        catch (InvalidOperationException)
        {
            // The process exited between HasExited and Kill.
        }

        await Completion.WaitAsync(cancellationToken);
    }

    public async ValueTask DisposeAsync()
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0) return;
        await TerminateAsync();
    }

    private async Task<int> MonitorAsync()
    {
        try
        {
            await _process.WaitForExitAsync();
            return _process.ExitCode;
        }
        finally
        {
            await CleanupCoreAsync();
            _process.Dispose();
        }
    }

    private async Task CleanupCoreAsync()
    {
        if (Interlocked.Exchange(ref _cleanupStarted, 1) != 0) return;

        Exception? remoteError = null;
        if (_revoker is not null && !string.IsNullOrWhiteSpace(Grant.SessionId))
        {
            try
            {
                using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(15));
                await _revoker(Grant.SessionId, timeout.Token);
            }
            catch (Exception exception)
            {
                // The target enforces its own expiry, so local secret cleanup must
                // continue even when an explicit best-effort revocation cannot reach it.
                RemoteRevocationError = remoteError = exception;
            }
        }

        await _relay.DisposeAsync();

        try
        {
            SshSessionLauncher.DeleteEphemeralFiles(_sessionDirectory, _privateKeyPath);
        }
        catch (Exception exception)
        {
            LocalCleanupError = exception;
            CleanupError = remoteError is null
                ? exception
                : new AggregateException(remoteError, exception);
            return;
        }

        CleanupError = remoteError;
    }
}

/// <summary>
/// Creates a per-session Ed25519 identity, asks the target Agent to authorize
/// only its public key, pins the returned host key, and opens an interactive SSH
/// client without consulting user or machine SSH configuration.
/// </summary>
public static class SshSessionLauncher
{
    public const int DedicatedPort = RemoteAdministrationProtocol.SshPort;
    internal const int MaximumRemoteCommandCharacters = 6000;
    private const int MaximumEncodedPowerShellCharacters = 5600;
    public static readonly TimeSpan MinimumLifetime = TimeSpan.FromMinutes(5);
    public static readonly TimeSpan MaximumLifetime = RemoteAdministrationProtocol.MaximumSshSession;
    private static readonly JsonSerializerOptions StrictProbeJson = new(JsonDefaults.Options)
    {
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
        PropertyNameCaseInsensitive = true
    };

    public static async Task<SshSessionHandle> LaunchAsync(
        SshSessionLaunchOptions options,
        SshSessionProvisioner provisioner,
        SshSessionRevoker? revoker = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(provisioner);
        ValidateExpectedHost(options.ExpectedHost);
        ValidateCommandOptions(options);
        if (options.RequestedLifetime < MinimumLifetime || options.RequestedLifetime > MaximumLifetime)
        {
            throw new ArgumentOutOfRangeException(
                nameof(options),
                $"SSH access must be requested for at least {MinimumLifetime.TotalMinutes:0} minutes and at most {MaximumLifetime.TotalHours:0} hours.");
        }

        CleanupStaleSessionDirectories();
        var ssh = RequireSystemOpenSshExecutable(options.SshExecutable, "ssh.exe");
        var sshKeygen = RequireSystemOpenSshExecutable(options.SshKeygenExecutable, "ssh-keygen.exe");
        var sessionDirectory = Path.Combine(
            AppPaths.AdminDataDirectory,
            "SshSessions",
            Guid.NewGuid().ToString("N"));
        var privateKeyPath = Path.Combine(sessionDirectory, "id_ed25519");
        var knownHostsPath = Path.Combine(sessionDirectory, "known_hosts");
        SshAccessResponse? grant = null;
        LoopbackSshRelay? relay = null;

        try
        {
            Directory.CreateDirectory(sessionDirectory);
            await RestrictSessionDirectoryAsync(sessionDirectory, cancellationToken);
            await GenerateEphemeralKeyAsync(sshKeygen, privateKeyPath, cancellationToken);

            var publicKey = NormalizePublicKey(
                await File.ReadAllTextAsync(privateKeyPath + ".pub", cancellationToken),
                "ephemeral client key");
            grant = await provisioner(publicKey, options.RequestedLifetime, cancellationToken)
                    ?? throw new InvalidDataException("The target returned an empty SSH access grant.");
            ValidateGrant(grant, options.ExpectedHost, options.RequestedLifetime);

            // Endpoint VPN products can allow Opticon's authenticated Agent API
            // traffic while denying a child ssh.exe direct access to the same
            // Tailscale peer. Keep the hardened Windows SSH client and all of its
            // key/host validation, but carry its TCP stream through this process.
            // The relay is loopback-only and exists for this one lease.
            relay = new LoopbackSshRelay(grant.Host, DedicatedPort);

            var hostKey = NormalizePublicKey(grant.HostPublicKey, "SSH host key");
            var knownHost = $"[{relay.Host}]:{relay.Port} {hostKey}{Environment.NewLine}";
            await File.WriteAllTextAsync(
                knownHostsPath,
                knownHost,
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
                cancellationToken);

            await VerifyRemoteAdministratorAsync(
                ssh,
                grant,
                privateKeyPath,
                knownHostsPath,
                relay.Host,
                relay.Port,
                cancellationToken);

            var remoteCommand = options.PowerShellEncodedCommand is null
                ? options.RemoteCommand
                : BuildExactPowerShellCommand(grant.SystemRoot, options.PowerShellEncodedCommand);
            var start = BuildStartInfo(
                ssh, grant, privateKeyPath, knownHostsPath,
                remoteCommand, options.AllocateTerminal, relay.Host, relay.Port);
            var process = new Process { StartInfo = start };
            if (!process.Start()) throw new InvalidOperationException("The Windows OpenSSH client did not start.");

            return new SshSessionHandle(
                process,
                grant,
                sessionDirectory,
                privateKeyPath,
                revoker,
                relay);
        }
        catch (Exception launchError)
        {
            if (grant is not null && revoker is not null && !string.IsNullOrWhiteSpace(grant.SessionId))
            {
                try
                {
                    using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(15));
                    await revoker(grant.SessionId, timeout.Token);
                }
                catch
                {
                    // The target-side lease still expires independently.
                }
            }

            if (relay is not null) await relay.DisposeAsync();

            try { DeleteEphemeralFiles(sessionDirectory, privateKeyPath); }
            catch (Exception cleanupError)
            {
                // Preserve the provisioning/validation exception as the primary error.
                // The attached diagnostic still exposes a rare local cleanup failure.
                launchError.Data["OpticonSshLocalCleanupError"] = cleanupError.ToString();
            }
            throw;
        }
    }

    internal static ProcessStartInfo BuildStartInfo(
        string sshExecutable,
        SshAccessResponse grant,
        string privateKeyPath,
        string knownHostsPath,
        string? remoteCommand = null,
        bool allocateTerminal = true,
        string? connectionHost = null,
        int? connectionPort = null)
    {
        if (remoteCommand is not null &&
            (string.IsNullOrWhiteSpace(remoteCommand) ||
             remoteCommand.Length > MaximumRemoteCommandCharacters ||
             remoteCommand.Contains('\0')))
            throw new ArgumentException(
                "The remote SSH command must be nonempty, contain no NUL characters, and be at most 6,000 characters.",
                nameof(remoteCommand));
        if (remoteCommand is not null && allocateTerminal)
            throw new ArgumentException("Automated SSH commands must not allocate a terminal.", nameof(allocateTerminal));

        var start = new ProcessStartInfo(sshExecutable)
        {
            UseShellExecute = false,
            CreateNoWindow = false,
            WindowStyle = ProcessWindowStyle.Normal,
            // The session directory already lives outside the installed app
            // and remains valid for the lifetime of ssh.exe. Explicitly using
            // it prevents an interactive SSH session from keeping Opticon's
            // install directory locked during an update.
            WorkingDirectory = Path.GetDirectoryName(privateKeyPath)
                ?? throw new ArgumentException("The SSH private-key path has no parent directory.", nameof(privateKeyPath))
        };

        // -F NUL prevents a local ssh_config from weakening host checking,
        // changing the destination, adding forwards, or selecting another key.
        Add(start, "-F", "NUL");
        Add(start, "-p", (connectionPort ?? DedicatedPort).ToString(System.Globalization.CultureInfo.InvariantCulture));
        Add(start, "-l", grant.UserName);
        Add(start, "-i", privateKeyPath);
        Add(start, "-o", "BatchMode=yes");
        Add(start, "-o", "IdentitiesOnly=yes");
        Add(start, "-o", "PreferredAuthentications=publickey");
        Add(start, "-o", "PasswordAuthentication=no");
        Add(start, "-o", "KbdInteractiveAuthentication=no");
        Add(start, "-o", "StrictHostKeyChecking=yes");
        Add(start, "-o", $"UserKnownHostsFile={knownHostsPath}");
        Add(start, "-o", "GlobalKnownHostsFile=NUL");
        Add(start, "-o", "UpdateHostKeys=no");
        Add(start, "-o", "CheckHostIP=yes");
        Add(start, "-o", "ClearAllForwardings=yes");
        Add(start, "-o", "ServerAliveInterval=30");
        Add(start, "-o", "ServerAliveCountMax=3");
        Add(start, "-o", "ConnectTimeout=15");
        start.ArgumentList.Add(allocateTerminal ? "-t" : "-T");
        start.ArgumentList.Add(connectionHost ?? grant.Host);
        if (remoteCommand is not null) start.ArgumentList.Add(remoteCommand);
        return start;
    }

    private static async Task VerifyRemoteAdministratorAsync(
        string sshExecutable,
        SshAccessResponse grant,
        string privateKeyPath,
        string knownHostsPath,
        string connectionHost,
        int connectionPort,
        CancellationToken cancellationToken)
    {
        var challenge = SecurityHelpers.CreateToken(32);
        var script = string.Join(';',
        [
            "$ErrorActionPreference='Stop'",
            "$probe=[IO.Path]::Combine($env:ProgramFiles,'Taildesk','UpdateGuardian','Taildesk.UpdateGuardian.exe')",
            "if(-not [IO.File]::Exists($probe)){exit 90}",
            $"& $probe '{RemoteAdministrationProtocol.SshAdminProbeArgument}' '{challenge}'",
            "exit $LASTEXITCODE"
        ]);
        var encoded = Convert.ToBase64String(Encoding.Unicode.GetBytes(script));
        var remoteCommand = BuildExactPowerShellCommand(grant.SystemRoot, encoded);
        var start = BuildStartInfo(
            sshExecutable,
            grant,
            privateKeyPath,
            knownHostsPath,
            remoteCommand,
            allocateTerminal: false,
            connectionHost,
            connectionPort);

        var result = await ProcessRunner.RunAsync(
            sshExecutable,
            start.ArgumentList,
            TimeSpan.FromSeconds(30),
            cancellationToken);
        if (!result.Succeeded)
            throw new UnauthorizedAccessException(
                "Opticon refused SSH because the target did not prove a full UAC-level administrator token. "
                + BoundedDiagnostic(result.StandardError, result.StandardOutput));

        var output = result.StandardOutput.Trim();
        if (output.Length is <= 0 or > 32 * 1024)
            throw new UnauthorizedAccessException("Opticon refused an invalid SSH administrator attestation.");

        SshAdminAttestation attestation;
        try
        {
            attestation = JsonSerializer.Deserialize<SshAdminAttestation>(output, StrictProbeJson)
                          ?? throw new JsonException("The response was empty.");
        }
        catch (JsonException exception)
        {
            throw new UnauthorizedAccessException("Opticon refused a malformed SSH administrator attestation.", exception);
        }

        var expectedUserSuffix = "\\" + RemoteAdministrationProtocol.SshAccountName;
        if (attestation.SchemaVersion != RemoteAdministrationProtocol.SshAdminProbeVersion
            || !SecurityHelpers.FixedTimeEquals(attestation.Challenge, challenge)
            || string.IsNullOrWhiteSpace(attestation.UserSid)
            || attestation.UserSid.Length > 184
            || attestation.UserSid.Equals("S-1-5-18", StringComparison.Ordinal)
            || string.IsNullOrWhiteSpace(attestation.UserName)
            || !attestation.UserName.EndsWith(expectedUserSuffix, StringComparison.OrdinalIgnoreCase)
            || !attestation.Elevated
            || attestation.ElevationType is not ("full" or "default")
            || attestation.IntegrityRid is < 0x3000 or >= 0x4000
            || !attestation.AdministratorsEnabled
            || !attestation.AdministrativeCapability
            || !attestation.TokenType.Equals("primary", StringComparison.Ordinal))
        {
            throw new UnauthorizedAccessException(
                "Opticon refused SSH because the target administrator token was filtered, mismatched, or insufficient.");
        }
    }

    private static string BoundedDiagnostic(params string[] values)
    {
        var value = FirstNonEmpty(values);
        value = value.Replace('\r', ' ').Replace('\n', ' ').Trim();
        return value.Length <= 512 ? value : value[..512] + "...";
    }

    private static void ValidateCommandOptions(SshSessionLaunchOptions options)
    {
        if (options.RemoteCommand is not null && options.PowerShellEncodedCommand is not null)
            throw new ArgumentException("Specify either a raw remote command or an encoded PowerShell command, not both.");
        if ((options.RemoteCommand is not null || options.PowerShellEncodedCommand is not null)
            && options.AllocateTerminal)
            throw new ArgumentException("Automated SSH commands must not allocate a terminal.");
        if (options.RemoteCommand is not null
            && (string.IsNullOrWhiteSpace(options.RemoteCommand)
                || options.RemoteCommand.Length > MaximumRemoteCommandCharacters
                || options.RemoteCommand.Contains('\0')))
            throw new ArgumentException(
                "The raw remote SSH command must be nonempty, contain no NUL characters, and be at most 6,000 characters.");
        if (options.PowerShellEncodedCommand is null) return;
        if (options.PowerShellEncodedCommand.Length is <= 0 or > MaximumEncodedPowerShellCharacters
            || options.PowerShellEncodedCommand.Any(character =>
                !char.IsAsciiLetterOrDigit(character) && character is not '+' and not '/' and not '='))
            throw new ArgumentException("The encoded PowerShell command is invalid.");
        try
        {
            var bytes = Convert.FromBase64String(options.PowerShellEncodedCommand);
            try
            {
                if (bytes.Length == 0 || bytes.Length % 2 != 0) throw new FormatException();
                if (!Convert.ToBase64String(bytes).Equals(options.PowerShellEncodedCommand, StringComparison.Ordinal))
                    throw new FormatException();
            }
            finally
            {
                CryptographicOperations.ZeroMemory(bytes);
            }
        }
        catch (FormatException exception)
        {
            throw new ArgumentException("The encoded PowerShell command is invalid.", exception);
        }
    }

    private static string BuildExactPowerShellCommand(string systemRoot, string encodedCommand)
    {
        if (string.IsNullOrWhiteSpace(systemRoot)
            || systemRoot.Length > 240
            || !Path.IsPathFullyQualified(systemRoot)
            || systemRoot.Any(character => char.IsWhiteSpace(character) || char.IsControl(character) || character is '"' or '\''))
            throw new InvalidDataException("The target returned an unsafe Windows system root for SSH automation.");
        var normalized = Path.GetFullPath(systemRoot).TrimEnd(Path.DirectorySeparatorChar);
        var powershell = Path.Combine(
            normalized, "System32", "WindowsPowerShell", "v1.0", "powershell.exe");
        return powershell + " -NoLogo -NoProfile -NonInteractive -EncodedCommand " + encodedCommand;
    }

    internal static void DeleteEphemeralFiles(string sessionDirectory, string privateKeyPath)
    {
        if (string.IsNullOrWhiteSpace(sessionDirectory) || !Directory.Exists(sessionDirectory)) return;

        try
        {
            if (File.Exists(privateKeyPath))
            {
                File.SetAttributes(privateKeyPath, FileAttributes.Normal);
                var length = new FileInfo(privateKeyPath).Length;
                using var stream = new FileStream(privateKeyPath, FileMode.Open, FileAccess.Write, FileShare.None);
                var zeroes = new byte[Math.Min(4096, Math.Max(1, (int)Math.Min(length, 4096)))];
                for (long written = 0; written < length; written += zeroes.Length)
                {
                    stream.Write(zeroes, 0, (int)Math.Min(zeroes.Length, length - written));
                }
                stream.Flush(flushToDisk: true);
            }
        }
        catch
        {
            // Best effort: deletion below is still more important than overwriting
            // a key file that may already have been removed or locked by the OS.
        }

        for (var attempt = 0; attempt < 3; attempt++)
        {
            try
            {
                foreach (var file in Directory.EnumerateFiles(sessionDirectory))
                    File.SetAttributes(file, FileAttributes.Normal);
                Directory.Delete(sessionDirectory, recursive: true);
                return;
            }
            catch when (attempt < 2)
            {
                Thread.Sleep(100);
            }
        }
    }

    private static async Task GenerateEphemeralKeyAsync(
        string sshKeygen,
        string privateKeyPath,
        CancellationToken cancellationToken)
    {
        var result = await ProcessRunner.RunAsync(
            sshKeygen,
            ["-q", "-t", "ed25519", "-N", string.Empty, "-C", "opticon-jit", "-f", privateKeyPath],
            TimeSpan.FromSeconds(30),
            cancellationToken);
        if (!result.Succeeded || !File.Exists(privateKeyPath) || !File.Exists(privateKeyPath + ".pub"))
        {
            throw new InvalidOperationException(
                "Windows ssh-keygen could not create an ephemeral Ed25519 key. " +
                FirstNonEmpty(result.StandardError, result.StandardOutput));
        }
    }

    private static async Task RestrictSessionDirectoryAsync(
        string sessionDirectory,
        CancellationToken cancellationToken)
    {
        if (!OperatingSystem.IsWindows()) throw new PlatformNotSupportedException("Windows OpenSSH is required.");
        var currentSid = WindowsIdentity.GetCurrent().User?.Value
                         ?? throw new InvalidOperationException("The current Windows user SID is unavailable.");
        var icacls = Path.GetFullPath(Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.Windows),
            "System32",
            "icacls.exe"));
        if (!File.Exists(icacls))
            throw new FileNotFoundException("The exact Windows ACL tool is unavailable.", icacls);
        var result = await ProcessRunner.RunAsync(
            icacls,
            [
                sessionDirectory,
                "/inheritance:r",
                "/grant:r",
                $"*{currentSid}:(OI)(CI)F",
                "*S-1-5-18:(OI)(CI)F"
            ],
            TimeSpan.FromSeconds(15),
            cancellationToken);
        if (!result.Succeeded)
        {
            throw new InvalidOperationException(
                "Opticon could not restrict its ephemeral SSH key directory. " + result.StandardError.Trim());
        }
    }

    private static string RequireSystemOpenSshExecutable(string? configuredPath, string fileName)
    {
        var system = Path.GetFullPath(Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.Windows),
            "System32",
            "OpenSSH",
            fileName));
        if (!string.IsNullOrWhiteSpace(configuredPath)
            && !string.Equals(
                Path.GetFullPath(Environment.ExpandEnvironmentVariables(configuredPath.Trim())),
                system,
                StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException($"Opticon SSH accepts only the Windows System32 OpenSSH {fileName} binary.");
        if (!File.Exists(system))
            throw new FileNotFoundException(
                $"Windows OpenSSH Client {fileName} is not installed. Install the Windows OpenSSH Client capability and retry.",
                system);
        return system;
    }

    private static void CleanupStaleSessionDirectories()
    {
        var root = Path.Combine(AppPaths.AdminDataDirectory, "SshSessions");
        if (!Directory.Exists(root)) return;
        var cutoff = DateTime.UtcNow - MaximumLifetime - TimeSpan.FromHours(1);
        foreach (var directory in Directory.EnumerateDirectories(root))
        {
            try
            {
                if (Directory.GetLastWriteTimeUtc(directory) < cutoff)
                    DeleteEphemeralFiles(directory, Path.Combine(directory, "id_ed25519"));
            }
            catch
            {
                // A live or locked session is left for the next reconciliation.
            }
        }
    }
    private static void ValidateExpectedHost(string host)
    {
        if (!IPAddress.TryParse(host, out var address)
            || address.AddressFamily != System.Net.Sockets.AddressFamily.InterNetwork
            || !IsTailscaleIpv4(address))
            throw new InvalidOperationException("Opticon SSH requires a target Tailscale IPv4 address.");
    }

    private static void ValidateGrant(
        SshAccessResponse grant,
        string expectedHost,
        TimeSpan requestedLifetime)
    {
        if (!IPAddress.TryParse(grant.Host, out var actual)
            || actual.AddressFamily != System.Net.Sockets.AddressFamily.InterNetwork
            || !IPAddress.TryParse(expectedHost, out var expected)
            || expected.AddressFamily != System.Net.Sockets.AddressFamily.InterNetwork
            || !actual.Equals(expected)
            || !IsTailscaleIpv4(actual))
        {
            throw new InvalidDataException("The target returned an SSH grant for a different address.");
        }
        if (grant.Port != DedicatedPort)
            throw new InvalidDataException($"Opticon SSH must use dedicated port {DedicatedPort}.");
        if (grant.CreatedAt is DateTimeOffset createdAt)
        {
            if (!RemoteAdministrationProtocol.IsSshLeaseWithinRequestedLifetime(
                    createdAt, grant.ExpiresAt, requestedLifetime))
                throw new InvalidDataException("The target returned an SSH lease longer than requested or already expired.");
        }
        else
        {
            // Compatibility with Agents that predate target-relative lease
            // durations. Their response contains only the legacy absolute expiry.
            var now = DateTimeOffset.UtcNow;
            if (grant.ExpiresAt <= now
                || grant.ExpiresAt > now.Add(requestedLifetime).AddMinutes(1))
                throw new InvalidDataException("The target returned an SSH lease longer than requested or already expired.");
        }
        if (string.IsNullOrWhiteSpace(grant.SessionId) || grant.SessionId.Length > 128
            || grant.SessionId.Any(character => !char.IsAsciiLetterOrDigit(character) && character is not '-' and not '_'))
            throw new InvalidDataException("The target returned an invalid SSH session identifier.");
        if (!string.Equals(grant.UserName, RemoteAdministrationProtocol.SshAccountName, StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException("The target returned an unexpected SSH administrator account.");
        // Normalization also rejects whitespace/quotes that would make exact shell invocation ambiguous.
        _ = BuildExactPowerShellCommand(grant.SystemRoot, "QQA=");
    }

    private static string NormalizePublicKey(string value, string description)
    {
        var parts = value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length < 2 || !parts[0].Equals("ssh-ed25519", StringComparison.Ordinal))
            throw new InvalidDataException($"The {description} is not an Ed25519 OpenSSH public key.");
        try
        {
            var decoded = Convert.FromBase64String(parts[1]);
            if (decoded.Length is < 32 or > 256) throw new FormatException();
        }
        catch (FormatException exception)
        {
            throw new InvalidDataException($"The {description} has invalid key data.", exception);
        }
        return $"{parts[0]} {parts[1]}";
    }

    private static bool IsTailscaleIpv4(IPAddress address)
    {
        if (address.AddressFamily != System.Net.Sockets.AddressFamily.InterNetwork) return false;
        var bytes = address.GetAddressBytes();
        return bytes[0] == 100 && bytes[1] is >= 64 and <= 127;
    }

    private static void Add(ProcessStartInfo start, string name, string value)
    {
        start.ArgumentList.Add(name);
        start.ArgumentList.Add(value);
    }

    private static string FirstNonEmpty(params string[] values) =>
        values.Select(value => value.Trim()).FirstOrDefault(value => value.Length > 0) ?? "No diagnostic output was returned.";
}
