<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Taildesk.Agent</AssemblyName>
    <RootNamespace>Taildesk.Agent</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Taildesk.Shared\Taildesk.Shared.csproj" />
  </ItemGroup>
</Project>
